apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaeger-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/o11y/jaeger
    type: DirectoryOrCreate
  storageClassName: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - convocate05
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-data
  namespace: o11y
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: jaeger-pv
  resources:
    requests:
      storage: 10Gi
