apiVersion: v1
kind: Service
metadata:
  name: convocate-api
  namespace: {{ .Values.global.namespace | default "convocate" }}
  labels:
    app: convocate-api
spec:
  selector:
    app: convocate-api
  ports:
    - port: {{ .Values.port | default 8443 }}
      targetPort: {{ .Values.port | default 8443 }}
      name: api
  type: ClusterIP
