apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: o11y
spec:
  secretName: prometheus-tls
  issuerRef:
    name: openbao-pki-internal
    kind: ClusterIssuer
  dnsNames:
    - prometheus
    - prometheus.o11y.svc
    - prometheus.o11y.svc.cluster.local
  duration: 24h
  renewBefore: 12h
