apiVersion: v1
kind: Service
metadata:
  name: convocate-ui
  namespace: {{ .Values.global.namespace | default "convocate" }}
spec:
  selector:
    app: convocate-ui
  ports:
    - port: {{ .Values.port | default 8080 }}
      targetPort: {{ .Values.port | default 8080 }}
      name: http
  type: ClusterIP
