version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "ci"
