version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src/api"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "gomod"
    directory: "/src/agent"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "gomod"
    directory: "/src/saml-scim-agent"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "gomod"
    directory: "/src/ui/cmd/serve"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "gomod"
    directory: "/o11y/metrics"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directory: "/src/ui"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/test/pdv"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/infrastructure/secrets/test"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/infrastructure/grafana/test"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/infrastructure/prometheus/test"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/infrastructure/k8s/test"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "docker"
    directory: "/infrastructure/docker"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "asymmetric-effort/convocate"
    labels:
      - "dependencies"
      - "ci"
