---
- name: Install Cilium CNI with OpenBao PKI
  hosts: control_plane_primary
  gather_facts: true
  become: true
  environment:
    TMPDIR: /var/tmp
    TEMP: /var/tmp
    TMP: /var/tmp
  roles:
    - role: ../roles/cilium
