/**
 * Build-time docs loader.
 *
 * Walks site/src/routes.ts, reads each referenced markdown file under
 * <repo>/docs, renders to HTML with `marked` + `highlight.js`, extracts
 * heading + first paragraph for SEO, and emits site/src/docs-data.ts as a
 * single TS module that the runtime imports synchronously.
 *
 * Iterative — no recursion (per project rule).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import hljs from 'highlight.js';
import { Marked } from 'marked';

import { allRoutes } from '../src/routes.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const outFile = resolve(here, '..', 'src', 'docs-data.ts');

interface Heading {
  level: number;
  text: string;
  id: string;
}

interface DocPage {
  title: string;
  description: string;
  html: string;
  headings: Heading[];
}

const slugify = (s: string): string =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');

const stripHtml = (s: string): string => s.replace(/<[^>]+>/g, '').trim();

const extractFirstParagraph = (md: string): string => {
  const lines = md.split('\n');
  let started = false;
  const buf: string[] = [];
  for (const raw of lines) {
    const line = raw.trim();
    if (!started) {
      if (line === '' || line.startsWith('#') || line.startsWith('>')) continue;
      started = true;
    }
    if (line === '') break;
    if (line.startsWith('#')) break;
    buf.push(line);
  }
  return stripHtml(buf.join(' ')).slice(0, 200);
};

const escapeForTemplate = (s: string): string =>
  s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const buildMarked = (headings: Heading[]): Marked => {
  const m = new Marked();
  m.use({
    renderer: {
      code(this: unknown, token: { text: string; lang?: string }) {
        const lang = (token.lang || '').trim().split(/\s+/)[0];
        let highlighted: string;
        if (lang && hljs.getLanguage(lang)) {
          highlighted = hljs.highlight(token.text, { language: lang, ignoreIllegals: true }).value;
        } else {
          highlighted = hljs.highlightAuto(token.text).value;
        }
        const cls = lang ? ` class="language-${lang} hljs"` : ' class="hljs"';
        return `<pre><code${cls}>${highlighted}</code></pre>`;
      },
      heading(this: unknown, token: { tokens: unknown[]; depth: number; text: string }) {
        // marked v18 passes a token object; use token.text for plain string.
        const text = token.text;
        const id = slugify(text);
        headings.push({ level: token.depth, text, id });
        return `<h${token.depth} id="${id}"><a class="anchor" href="#${id}">#</a> ${text}</h${token.depth}>`;
      },
    },
  });
  return m;
};

interface DocsData {
  [path: string]: DocPage;
}

const data: DocsData = {};

for (const route of allRoutes) {
  const srcPath = resolve(repoRoot, route.source);
  const md = readFileSync(srcPath, 'utf8');

  // Title: first H1 if present, else route.title
  const titleMatch = md.match(/^#\s+(.+?)\s*$/m);
  const title = titleMatch ? titleMatch[1].trim() : route.title;
  const description = extractFirstParagraph(md);

  const headings: Heading[] = [];
  const marked = buildMarked(headings);
  const html = await marked.parse(md);

  data[route.path] = {
    title,
    description,
    html: typeof html === 'string' ? html : String(html),
    headings,
  };
}

const banner = `/**
 * AUTO-GENERATED by scripts/build-docs-data.ts. Do not edit by hand.
 * Each entry maps a hash route to the rendered HTML + metadata for one
 * markdown source file under <repo>/docs.
 */
`;

const body =
  `export interface DocHeading { level: number; text: string; id: string }\n` +
  `export interface DocPage { title: string; description: string; html: string; headings: DocHeading[] }\n` +
  `export const docsData: Record<string, DocPage> = {\n` +
  Object.entries(data)
    .map(
      ([path, page]) =>
        `  ${JSON.stringify(path)}: {\n` +
        `    title: ${JSON.stringify(page.title)},\n` +
        `    description: ${JSON.stringify(page.description)},\n` +
        `    headings: ${JSON.stringify(page.headings)},\n` +
        `    html: \`${escapeForTemplate(page.html)}\`,\n` +
        `  },`,
    )
    .join('\n') +
  `\n};\n`;

writeFileSync(outFile, banner + body, 'utf8');

const pageCount = Object.keys(data).length;
console.log(`build-docs-data: wrote ${outFile} (${pageCount} pages)`);
