apiVersion: v1
kind: Service
metadata:
  name: ginger
  namespace: {{ .Values.global.namespace | default "o11y" }}
spec:
  selector:
    app: ginger
  ports:
    - port: 4318
      targetPort: 4318
      name: otlp-http
    - port: 16686
      targetPort: 16686
      name: query
    - port: 14269
      targetPort: 14269
      name: admin
  type: ClusterIP
