apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://192.168.3.165:443
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      tlsSkipVerify: true
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: https://192.168.3.167:443
    editable: true
    jsonData:
      tlsSkipVerify: true
