apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbao-pv
spec:
  capacity:
    storage: {{ .Values.storage | default "1Gi" }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath | default "/mnt/security/openbao" }}
    type: DirectoryOrCreate
  storageClassName: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.nodeAffinity | default "node-b-3" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-data
  namespace: {{ .Values.global.namespace | default "security" }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: openbao-pv
  resources:
    requests:
      storage: {{ .Values.storage | default "1Gi" }}
