services:
  secrets-a:
    image: 192.168.3.90:5000/convocate/openbao:latest
    container_name: secrets-a
    restart: unless-stopped
    ports:
      - "192.168.3.160:8200:8200"
    volumes:
      - /var/openbao/secrets-a:/openbao/data
      - /var/openbao/tls/secrets-a:/openbao/tls:ro
      - ./config/openbao-config-secrets-a.hcl:/openbao/config/config.hcl:ro
    environment:
      BAO_API_ADDR: "https://192.168.3.160:8200"
      BAO_CLUSTER_ADDR: "https://192.168.3.160:8201"
    cap_add:
      - IPC_LOCK

  secrets-b:
    image: 192.168.3.90:5000/convocate/openbao:latest
    container_name: secrets-b
    restart: unless-stopped
    ports:
      - "192.168.3.161:8200:8200"
    volumes:
      - /var/openbao/secrets-b:/openbao/data
      - /var/openbao/tls/secrets-b:/openbao/tls:ro
      - ./config/openbao-config-secrets-b.hcl:/openbao/config/config.hcl:ro
    environment:
      BAO_API_ADDR: "https://192.168.3.161:8200"
      BAO_CLUSTER_ADDR: "https://192.168.3.161:8201"
    cap_add:
      - IPC_LOCK
