apiVersion: v2
name: convocate
description: Convocate platform umbrella chart
version: 0.1.2
appVersion: "1.0.0"
type: application
dependencies:
  - name: api
    version: 0.1.0
    condition: api.enabled
  - name: ui
    version: 0.1.0
    condition: ui.enabled
  - name: postgresql
    version: 0.1.0
    condition: postgresql.enabled
  - name: redis
    version: 0.1.0
    condition: redis.enabled
  - name: minio
    version: 0.1.0
    condition: minio.enabled
  - name: influxdb
    version: 0.1.0
    condition: influxdb.enabled
  - name: prometheus
    version: 0.1.0
    condition: prometheus.enabled
  - name: grafana
    version: 0.1.0
    condition: grafana.enabled
  - name: ginger
    version: 0.1.0
    condition: ginger.enabled
  - name: fluentbit
    version: 0.1.0
    condition: fluentbit.enabled
  - name: node-metrics
    version: 0.1.0
    condition: node-metrics.enabled
  - name: openbao
    version: 0.1.0
    condition: openbao.enabled
