global:
  imageTag: "latest"
  registry: "ghcr.io/asymmetric-effort"
  namespace: "convocate"
  domain: "prod.convocate.net"

api:
  enabled: true
  hostNetwork: false
  useHostPort: true
  listenAddr: ":443"
  port: 443
  nodeSelector:
    kubernetes.io/hostname: node-b-1
  tls:
    enabled: true
    secretName: convocate-api-tls
  env:
    OPENBAO_ADDR: "https://192.168.3.161:443"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi

postgresql:
  enabled: true
  storage: 10Gi
  nodeAffinity: node-b-4

redis:
  enabled: true
  nodeAffinity: node-b-3

# Disable services managed outside K8s or not needed on production
ui:
  enabled: false
minio:
  enabled: false
influxdb:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
ginger:
  enabled: false
fluentbit:
  enabled: false
node-metrics:
  enabled: false
openbao:
  enabled: false
