global:
  imageTag: "latest"
  registry: "ghcr.io/asymmetric-effort"
  namespace: "convocate"
  domain: "dev.convocate.net"

api:
  enabled: true
  listenAddr: ":8443"
  port: 8443
  tls:
    enabled: false
    secretName: convocate-api-tls
  ingress:
    enabled: true
  env:
    OPENBAO_ADDR: "https://192.168.3.161:443"
    SAML_SCIM_AGENT_URL: "https://192.168.3.168:443"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

postgresql:
  enabled: true
  storage: 2Gi
  nodeAffinity: node-a-3

redis:
  enabled: true
  nodeAffinity: node-a-4

# Disable services managed outside K8s or not needed on canary
ui:
  enabled: true
  port: 8080
  ingress:
    enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 500m
      memory: 256Mi
minio:
  enabled: false
influxdb:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
ginger:
  enabled: false
fluentbit:
  enabled: false
node-metrics:
  enabled: false
openbao:
  enabled: false
