apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: {{ .Values.storage | default "5Gi" }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath | default "/mnt/o11y/grafana" }}
    type: DirectoryOrCreate
  storageClassName: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.nodeAffinity | default "convocate05" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{ .Values.global.namespace | default "o11y" }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: grafana-pv
  resources:
    requests:
      storage: {{ .Values.storage | default "5Gi" }}
