apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influxdb-tls
  namespace: {{ .Values.global.namespace | default "o11y" }}
spec:
  secretName: influxdb-tls
  issuerRef:
    name: openbao-pki-internal
    kind: ClusterIssuer
  dnsNames:
    - influxdb
    - influxdb.{{ .Values.global.namespace | default "o11y" }}.svc
    - influxdb.{{ .Values.global.namespace | default "o11y" }}.svc.cluster.local
  duration: 24h
  renewBefore: 12h
