apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
spec:
  capacity:
    storage: {{ .Values.storage | default "100Gi" }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath | default "/mnt/o11y/influxdb" }}
    type: DirectoryOrCreate
  storageClassName: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.nodeAffinity | default "node-b-4" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: {{ .Values.global.namespace | default "o11y" }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: influxdb-pv
  resources:
    requests:
      storage: {{ .Values.storage | default "100Gi" }}
