apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: o11y
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "convocate-grafana"
  INFLUXDB_TOKEN: "convocate-influx-token"
