apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: o11y
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "convocate-grafana"
  INFLUXDB_TOKEN: "convocate-influx-token"
  OPENBAO_OIDC_CLIENT_ID: "dPvNprfTx3rReDZu4fXNPTEolTsNcdaq"
  OPENBAO_OIDC_CLIENT_SECRET: "hvo_secret_PzGedNyvBKVsxOrWfJJbGFRDakymw7k4FiCCe5NJwzHYIS1rBME9firrPg9sQAOD"
