apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbao-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/security/openbao
    type: DirectoryOrCreate
  storageClassName: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - convocate04
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-data
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: openbao-pv
  resources:
    requests:
      storage: 1Gi
