apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: influxdb-selfsigned
  namespace: convocate
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influxdb-tls
  namespace: convocate
spec:
  secretName: influxdb-tls
  issuerRef:
    name: influxdb-selfsigned
    kind: Issuer
  dnsNames:
    - influxdb
    - influxdb.convocate.svc
    - influxdb.convocate.svc.cluster.local
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
