apiVersion: v1
kind: Secret
metadata:
  name: influxdb-credentials
  namespace: o11y
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_PASSWORD: "convocate-influx"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "convocate-influx-token"
