apiVersion: v1
kind: Service
metadata:
  name: convocate-ui
  namespace: convocate
spec:
  selector:
    app: convocate-ui
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
